// Чат
export const OPEN_CHAT = 'OPEN_CHAT';
export const AUTO_OPEN_CHAT = 'AUTO_OPEN_CHAT';

export const CLOSE_CHAT = 'CLOSE_CHAT';

export const OPEN_DIALOG = 'OPEN_DIALOG';
export const OPEN_CONTACTS = 'OPEN_CONTACTS';

// Диалог
export const POST_MESSAGE_REQUEST = 'POST_MESSAGE_REQUEST';
export const POST_MESSAGE_OK = 'POST_MESSAGE_OK';
export const POST_MESSAGE_FAIL = 'POST_MESSAGE_FAIL';

export const LOAD_MESSAGE_REQUEST = 'LOAD_MESSAGE_REQUEST';
export const LOAD_MESSAGE_OK = 'LOAD_MESSAGE_OK';
export const LOAD_MESSAGE_FAIL = 'LOAD_MESSAGE_FAIL';

// Контакты
export const POST_CONTACTS_REQUEST = 'POST_CONTACTS_REQUEST';
export const POST_CONTACTS_OK = 'POST_CONTACTS_OK';
export const POST_CONTACTS_FAIL = 'POST_CONTACTS_FAIL';

export const LOAD_CONTACTS_REQUEST = 'LOAD_CONTACTS_REQUEST';
export const LOAD_CONTACTS_OK = 'LOAD_CONTACTS_OK';
export const LOAD_CONTACTS_FAIL = 'LOAD_CONTACTS_FAIL';
